### ISSUE TITLE
Semantic connection of any individual to documents

### ISSUE THREAD

**Issue by kdaveed** [RDFBones/RDFBones-O#1]
How can documents be linked to individuals? 
Analogous to _hasProfileImage_, which connects _Person_ instances with _Image_ instances.

**Comment by kdaveed** [comment]
@cuboideum commented on this issue in [issue 1 of RDFBones](https://github.com/RDFBones/RDFBones/issues/1)

> The VIVO ontology uses the 'is about' (obo:IAO_0000136) property in order to express that a document contains information on something (i.e. that something can be seen in a picture). The 'related documents' (bibo:presents) is claimed to 'relate an event to associated documents'. However, the inverse property 'presented at event' (bibo:presentedAt) makes quite clear that the actual meaning is more restricted. But the other possible meanings are already covered by the faux property 'output of process or event', based on 'has output' (obo:RO_0002353). Authors, editors are defined by respective faux properties.

> What would be the exact usage of 'hasDocument'?

> Would 'hasImage' not be a subpredicate of 'hasDocument', since bibo:Image is a subclass of bibo:Document?

> By my understanding, the file store is mostly relevant to profile pages for instances of 'Document' or its subclasses. Only there you can upload a file. What is your idea?

> The only reason why predicates should be concerned at all is when you intend to have image thumbnails along with links to instances of 'Image'. Probably we would need an inverse property of 'is about' here and possibly more properties to indicate more specific types of depiction?

**Comment by cuboideum** [comment]
I assume that "_hasProfileImage_" refers to _vitro-public:Image_? I also assume that this property is used to refer an image file (range: _vitro-public:File_) to a profile page? In this case, one or more analogous properties will have to be created on application level, analogous to _vitro-public_. An attempt in this direction is [#11: 'File Ontology' of RDFBones](https://github.com/RDFBones/RDFBones/issues/11), I suppose.

I further assume that the real question for this issue is the following: Which properties link instances of _bibo:Document_ or its subclasses to instances of any kind? So it would be about how to specify that a certain bone is depicted in a photograph. Or that the same photograph also shows pathological traces that were diagnosed elsewhere. Or that a certain result was mentioned in a lab report.

Are my assumptions correct? @kdaveed If this is the case, please edit the original issue message accordingly.

**Comment by cuboideum** [comment]
This graph illustrates the properties that are displayed in VIVO 1.8 if a new instance of the class bibo:Document is created:

![rdfbones_document](https://cloud.githubusercontent.com/assets/8103073/10163321/69e14d08-66b2-11e5-921e-b016333f703f.png)

**Comment by kdaveed** [comment]
>I further assume that the real question for this issue is the following: Which properties link instances of bibo:Document or its subclasses to instances of any kind? So it would be about how to specify that a certain bone is depicted in a photograph. Or that the same photograph also shows pathological traces that were diagnosed elsewhere. Or that a certain result was mentioned in a lab report.
@cuboideum  Your assumption is correct. This is the question.

How do we connect persons with individuals is already solved by the _vivo:featured_in_ predicate. If I click on the person profile page in the Publications property group on the predicate  _vivo:featured_in_ then the following page appears. 

![screen shot 2015-10-01 at 18 39 41](https://cloud.githubusercontent.com/assets/7580884/10227144/fc455d50-686b-11e5-9aef-4433eceeebfa.png)

**Comment by cuboideum** [comment]
I have started a [wiki page](https://github.com/RDFBones/RDFBones-O/wiki/Documents) on how to link documents to other elements.
