### ISSUE TITLE
[RDFBones-O] Use # instead of / for defining hasMissingMaterialLabel

### ISSUE THREAD

**Issue by zarquon42b** [RDFBones/RDFBones-O#171]
<http://w3id.org/rdfbones/core/hasMissingMaterialLabel> => <http://w3id.org/rdfbones/core#hasMissingMaterialLabel>

**Comment by zarquon42b** [comment]
phaleron-di

**Comment by cuboideum** [comment]
The problem persisted because the Phaleron-DentalInventory submodule containing the RDFBones core ontology had not been updated. This inserted an outdated ontology version into the workflow. This is corrected in commit https://github.com/RDFBones/Phaleron-DentalInventory/commit/f50f29c740bafee26771055868ede6ec57bbe7bf.

**Comment by cuboideum** [comment]
The Phaleron App Ontology has been updated with commit https://github.com/AnthroGraph/Phaleron-AppOntology/commit/61b5ddab9ff9ddabab1e898e0053afc070b4722a to incorporate these changes. There are currently no RDFBones URIs with / in place of # in the script output. Thsi resolves the issue.
