### ISSUE TITLE
[phaleron-patho] ImpossibilityOfObservation => ObservationImpossible 

### ISSUE THREAD

**Issue by zarquon42b** [RDFBones/RDFBones-O#174]
Please change all instances `phaleron-patho:ImpossibilityOfObservation` to `phaleron-patho:ObservationImpossible`

**Comment by cuboideum** [comment]
Fixed with pull request https://github.com/RDFBones/Phaleron-DentalInventory/pull/2. The Phaleron app ontology has been updated with commit https://github.com/AnthroGraph/Phaleron-AppOntology/commit/ad2475d82eabde1623ec2f61e20bf96895d9909d.

As in previous cases, the error arose from an incorrect element in RDFGraphics that has been copied and pasted in various building plans. The affected file has been corrected with pull request https://github.com/RDFBones/RDFBonesGraphics/pull/8.
