### ISSUE TITLE
[phaleron-patho] Wrong class in Create New PBP-Paleopathology Instance query

### ISSUE THREAD

**Issue by 15E601** [RDFBones/RDFBones-O#175]
Was browsing Ontodia and noticed this:
![Screenshot from 2023-01-19 19-38-19](https://user-images.githubusercontent.com/67172847/213531809-4bef1f2a-ec7d-40c2-bf94-77d896228695.png)
Class _phaleron-patho:PaleopathologyInvestigation_ isn't linked to any ontology. There's an error in the creation query.

The SPARQL line
`?myPPprocess a <http://w3id.org/rdfbones/ext/phaleron-patho/PaleopathologyInvestigation> .`
in the template http://www.metaphacts.com/resource/PBP_Patho_CreatePaleopath needs to be changed to
`?myPPprocess a <http://w3id.org/rdfbones/ext/phaleron-patho/PaleopathologicalInvestigation> .`
which is the actual class in _phaleron-patho_

**Comment by zarquon42b** [comment]
Suggestion: rename the class in the ontology, as there is already an existing class called `<http://w3id.org/rdfbones/ext/phaleron-dpatho/DentalPaleopathologyInvestigation>` and the naming would be more consistent that way.
I now also assigned @cuboideum to look into this.

**Comment by cuboideum** [comment]
Of course it is possible to change the URI of the class. But are you sure you have not referenced the existing URI elsewhere in AnthroGraph?

**Comment by cuboideum** [comment]
@zarquon42b: What ist the verdict? Shall I change the class URI in the ontology?

**Comment by zarquon42b** [comment]
We are currently only using `<http://w3id.org/rdfbones/ext/phaleron-patho/PaleopathologyInvestigation>` throughout the database which is not defined. I would suggest changing the URI of 
`<http://w3id.org/rdfbones/ext/phaleron-patho/PaleopathologicalInvestigation>` to `<http://w3id.org/rdfbones/ext/phaleron-patho/PaleopathologyInvestigation>`.
Otherwise I have to fix those triples as well.
Can we please not make it a habit of changing URIs of classes already deployed?
BTW: My original statement is from January - before we implemented and deployed it.

**Comment by cuboideum** [comment]
Pull request https://github.com/RDFBones/Phaleron-Pathologies/pull/21 makes the requested change to the Phaleron-Pathologies ontology extension.

**Comment by cuboideum** [comment]
Commit https://github.com/AnthroGraph/Phaleron-AppOntology/commit/fd15c548e3e13be015f6c7091634bc1b2747f514 updates the Phaleron app ontology.
