### ISSUE TITLE
[Phaleron-AgeEstimation] Add role specific subclasses of AgeEstimationProcess, AgeEstimationDataset & PubicAgeEstimationDatasetSection

### ISSUE THREAD

**Issue by zarquon42b** [RDFBones/RDFBones-O#187]
Add role specific subclasses of AgeEstimationProcess, AgeEstimationDataset & PubicAgeEstimationDatasetSection.

**Comment by cuboideum** [comment]
To clarify the request:

AnthroGraph is built from a series of pages (entry forms or display pages) that display information about individuals of a certain class in a specified way. Each of the underlying templates needs to be related to a specific class. As age estimation can be carried out in the context of several sex-based roles, these contexts need to be reflected by context-specific classes.

I suggest the following solution:

1. Create role-specific subclasses of phaleron-ae:AgeEstimationProcess. This documents how sex-based roles influence the investigation.
2. Create role-specific subclasses of phaleron-ae:AgeEstimationDataset and phaleron-ae:PubicAgeEstimationDatasetSection in the Phaleron app ontology. Datasets are intended to define how output should be structured and have little bearing on content. Role-specific subclasses in the ontology extension would cause confusion.

**Comment by cuboideum** [comment]
On second thoughts, it is actually impossible to create subclasses of phaleron-ae:AgeEstimationProcess that are specific to the sex-based role the input specimens have in the investigation because the process phaleron-ae:AssigningASexBasedRoleForAgeEstimation is part of the investigation. Creating a specific type of investigation would preempt this classification.

As a consequence, all desired changes need to be defined in the Phaleron App Ontology and not in the ontology extension.

**Comment by cuboideum** [comment]
Updated issue https://github.com/AnthroGraph/Phaleron-AppOntology/issues/31 to include all requested changes.
