### ISSUE TITLE
Spelling mistake in rdfbones:isDepicted

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBones-O#30]
Correct spelling mistake in rdfbones:isDepicted, reported by @zarquon42b on 15 March 2016.

**Comment by kdaveed** [comment]
@cuboideum @zarquon42b 
Right now there are isDepicted predicate : 

![screen shot 2016-05-11 at 21 17 38](https://cloud.githubusercontent.com/assets/7580884/15193361/d436ce82-17bd-11e6-97db-f4f741775ff8.png)

Please delete the isDepicted and correct the isDepiceted to isDepicted, because the domain and range class definitions are necessary for the appearance of the field on the profile pages, and therefore as well for the pull request of the customViewFormImg branch.
